### ISSUE TITLE
Parametric Model

### ISSUE THREAD

**Issue by elishafer** [wuphilipp/robot_parts#1]
Hi,
Could you share a parametric model of the shell? I'd like to see if it'll fit the unitree go1, also it'll give me the possibility to customise/improve on the model. If you have onshape that would be best.

**Comment by wuphilipp** [comment]
Hi! Sorry, I just saw your issue. Unfortunately I'm not using onshape and am currently not planning on releasing the parametric model as everyone uses their own preferred software (may of which are proprietary). I did however just add my model for the Go1, so hopefully that can help!

**Comment by elishafer** [comment]
Thanks @wuphilipp for uploading the model for Go1!
I think that in the future, myself and others may find it useful to modify your model. Afaik, most CAD modeling software gives the option to export in parasolid format (.x_t). Although the modeling history will be erased, we will be able to modify the model.
Is there any chance you can upload the parasolid file?

**Comment by wuphilipp** [comment]
Hey @elishafer ! Thanks for the suggestion and sorry about the delay! (forgot about this since i had closed the issue). I just uploaded STEP and x_t formats! Hope this helps!
